export const NG_CONDUIT_TOKEN = 'NG_CONDUIT_TOKEN';
export const NG_CONDUIT_USER = 'NG_CONDUIT_USER';
export const BASE_URL = 'BASE_URL';
export const PROFILE_ARTICLES_TYPE = 'PROFILE_ARTICLES_TYPE';
